[package]
name = "igneous"
authors = [ "c1m50c <https://github.com/c1m50c>" ]
version = "0.1.0"
edition = "2021"

[dependencies]
igneous-components = { path = "components/" }
iced = "0.6.0"

[workspace]
members = [ "components/" ]
