[package]
name = "igneous-types"
authors = [ "c1m50c <https://github.com/c1m50c>" ]
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.151", features = ["derive"] }
ron = "0.8.0"
