[package]
name = "igneous-components"
authors = [ "c1m50c <https://github.com/c1m50c>" ]
version = "0.0.0"
edition = "2021"

[dependencies]
igneous-types = { path = "../types" }
eframe = "0.20.1"
egui = "0.20.1"
